# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cast < Formula
  desc "Typecast Text-to-Speech CLI"
  homepage "https://github.com/neosapience/cast"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neosapience/cast/releases/download/v0.1.0/cast_darwin_amd64.tar.gz"
      sha256 "73dac4974b3718d44427970d9872f7e75d7f686f0174491e00e5be0fd2f95891"

      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neosapience/cast/releases/download/v0.1.0/cast_darwin_arm64.tar.gz"
      sha256 "76e4e48c1e3b69e0e125445ea0ebf5b32eaadbfb060d93756715d9e4ebcc35d9"

      define_method(:install) do
        bin.install "cast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v0.1.0/cast_linux_amd64.tar.gz"
      sha256 "c0a2382db3ac6016485b36b1d445823420bd5d5e0231acdfdc5c151a868fc516"
      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v0.1.0/cast_linux_arm64.tar.gz"
      sha256 "2947e5bf4bd3e599ccc8554cbdf4e8fd889a706862e49a3080e5f2af41e13735"
      define_method(:install) do
        bin.install "cast"
      end
    end
  end
end
