# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cast < Formula
  desc "Typecast Text-to-Speech CLI"
  homepage "https://github.com/neosapience/cast"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neosapience/cast/releases/download/v1.0.2/cast_darwin_amd64.tar.gz"
      sha256 "fd5be0d67ff60e292a134bdacf7147ce1bd9a3794c8fdcb2eac89fd71ecd3e35"

      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neosapience/cast/releases/download/v1.0.2/cast_darwin_arm64.tar.gz"
      sha256 "89291a26effc6db3eb4ace7fb2e654b5d9d1b045626c783703d320aa014fb21f"

      define_method(:install) do
        bin.install "cast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v1.0.2/cast_linux_amd64.tar.gz"
      sha256 "8edc9092fb35efcadc28641b1850d0154941210c78d39ab95cfee66784d465f0"
      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v1.0.2/cast_linux_arm64.tar.gz"
      sha256 "889c184b86cede6d999ddd2c0c805dc6ae341b61962ea43e38d71df84a7b0289"
      define_method(:install) do
        bin.install "cast"
      end
    end
  end
end
