# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cast < Formula
  desc "Typecast Text-to-Speech CLI"
  homepage "https://github.com/neosapience/cast"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neosapience/cast/releases/download/v1.0.1/cast_darwin_amd64.tar.gz"
      sha256 "4bec594ed176d90d5333b662fe1ea62df1f94f730f885ba556993c7dc394149d"

      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neosapience/cast/releases/download/v1.0.1/cast_darwin_arm64.tar.gz"
      sha256 "9533dfce58500e74edab97c5ad597115314ad67141cbac64ad13d324629de3b2"

      define_method(:install) do
        bin.install "cast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v1.0.1/cast_linux_amd64.tar.gz"
      sha256 "13b14319b3d3663e959fca121fbd1f4b9af4985b6563e2a7db4110ae85ef5af3"
      define_method(:install) do
        bin.install "cast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neosapience/cast/releases/download/v1.0.1/cast_linux_arm64.tar.gz"
      sha256 "52ac146b02d47534be7afe6c732f21f1bd4d5f32ecfe41b0165f94581886f2f7"
      define_method(:install) do
        bin.install "cast"
      end
    end
  end
end
